apiVersion: v1
entries:
  rampart-ui:
  - apiVersion: v2
    appVersion: 2.0.0-dev.snapshot
    created: "2023-08-30T13:41:54.817230368Z"
    description: A Helm chart rampart ui
    digest: e53908bfae24a15948baa860aa9f107fb6d20713b407f91f336410ba89034ccd
    name: rampart-ui
    type: application
    urls:
    - https://rampart-aios.github.io/charts%22/charts/rampart-ui-0.2.0-xxxxx.tgz
    version: 0.2.0-xxxxx
generated: "2023-08-30T13:41:54.816582156Z"
