annotations:
  petuum.com/rampartComponent: "inputs:\n- name: hello \n  type: volume\n- name: input_2\n
    \ type: not_a_type\noutputs:\n- name: stave_sql_output\n  type: volume\n"
apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: test_helm_invalid_b
type: application
version: 0.6.0
